name: CD- Deploy

on:
  workflow_dispatch

jobs:
  cd:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Docker login
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: docker build -t model_testing .
      - name: Tags
        run: |
          docker tag model_testing ${{ secrets.DOCKER_USER }}/front:${{ github.sha }}
          docker tag model_testing ${{ secrets.DOCKER_USER }}/front:latest
      - name: Push
        run: |
          docker push ${{ secrets.DOCKER_USER }}/front:${{ github.sha }}
          docker push ${{ secrets.DOCKER_USER }}/front:latest